In [1]:

import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\Sandeep\\OneDrive\\Documents\\Projects\\IPL-Performance-Intelligence\\data\\raw\\IPL.csv")

C:\Users\Sandeep\AppData\Local\Temp\ipykernel_17708\758258734.py:1: DtypeWarning: Columns (0: review_batter, 1: team_reviewed, 2: review_decision, 3: umpire, 4: season, 5: superover_winner, 6: result_type, 7: method, 8: event_match_no) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:\\Users\\Sandeep\\OneDrive\\Documents\\Projects\\IPL-Performance-Intelligence\\data\\raw\\IPL.csv")

In [3]:
df.head()

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,striker_out,next_batter
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,...,1,0,NaN,NaN,0,1,0,BB McCullum|SC Ganguly,0,NaN
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,...,2,0,NaN,NaN,0,1,0,BB McCullum|SC Ganguly,0,NaN
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,2,0,NaN,NaN,0,1,0,BB McCullum|SC Ganguly,0,NaN
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,3,0,NaN,NaN,0,2,0,BB McCullum|SC Ganguly,0,NaN
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,...,4,0,NaN,NaN,0,3,0,BB McCullum|SC Ganguly,0,NaN

In [4]:
df.shape

(295732, 64)

In [5]:
df.columns

Index(['match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter',
       'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
       'batting_partners', 'striker_out', 'next_batter'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 295732 entries, 0 to 295731
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           295732 non-null  int64
 1   date               295732 non-null  str
 2   match_type         295732 non-null  str
 3   event_name         295732 non-null  str
 4   innings            295732 non-null  int64
 5   batting_team       295732 non-null  str
 6   bowling_team       295732 non-null  str
 7   over               295732 non-null  int64
 8   ball               295732 non-null  int64
 9   ball_no            295732 non-null  float64
 10  batter             295732 non-null  str
 11  bat_pos            295732 non-null  int64
 12  runs_batter        295732 non-null  int64
 13  balls_faced        295732 non-null  int64
 14  bowler             295732 non-null  str
 15  valid_ball         295732 non-null  int64
 16  runs_extras        295732 non-null  int64
 17  runs_total         295732 non-null  int64
 18  runs_bowler        295732 non-null  int64
 19  runs_not_boundary  295732 non-null  bool
 20  extra_type         16227 non-null   str
 21  non_striker        295732 non-null  str
 22  non_striker_pos    295732 non-null  int64
 23  wicket_kind        14705 non-null   str
 24  player_out         14705 non-null   str
 25  fielders           10721 non-null   str
 26  runs_target        142303 non-null  float64
 27  review_batter      990 non-null     str
 28  team_reviewed      990 non-null     str
 29  review_decision    990 non-null     str
 30  umpire             990 non-null     str
 31  umpires_call       295732 non-null  bool
 32  player_of_match    295732 non-null  str
 33  match_won_by       295732 non-null  str
 34  win_outcome        290752 non-null  str
 35  toss_winner        295732 non-null  str
 36  toss_decision      295732 non-null  str
 37  venue              295732 non-null  str
 38  city               295732 non-null  str
 39  day                295732 non-null  int64
 40  month              295732 non-null  int64
 41  year               295732 non-null  int64
 42  season             295732 non-null  object
 43  gender             295732 non-null  str
 44  team_type          295732 non-null  str
 45  superover_winner   4152 non-null    str
 46  result_type        4980 non-null    str
 47  method             4131 non-null    str
 48  balls_per_over     295732 non-null  int64
 49  overs              295732 non-null  int64
 50  event_match_no     295732 non-null  object
 51  stage              295732 non-null  str
 52  match_number       295732 non-null  str
 53  team_runs          295732 non-null  int64
 54  team_balls         295732 non-null  int64
 55  team_wicket        295732 non-null  int64
 56  new_batter         14163 non-null   str
 57  power_surge_start  0 non-null       float64
 58  batter_runs        295732 non-null  int64
 59  batter_balls       295732 non-null  int64
 60  bowler_wicket      295732 non-null  int64
 61  batting_partners   295732 non-null  str
 62  striker_out        295732 non-null  int64
 63  next_batter        14163 non-null   str
dtypes: bool(2), float64(3), int64(24), object(2), str(33)
memory usage: 140.5+ MB

In [7]:
df.describe()

,match_id,innings,over,ball,ball_no,bat_pos,runs_batter,balls_faced,valid_ball,runs_extras,...,balls_per_over,overs,team_runs,team_balls,team_wicket,power_surge_start,batter_runs,batter_balls,bowler_wicket,striker_out
count,2.957320e+05,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,...,295732.0,295732.0,295732.000000,295732.000000,295732.000000,0.0,295732.000000,295732.000000,295732.000000,295732.000000
mean,9.770551e+05,1.482728,9.190331,3.488807,9.539212,3.621847,1.290117,0.966605,0.962459,0.068336,...,6.0,20.0,78.146291,58.592844,2.466067,NaN,18.514882,13.982883,0.045609,0.047793
std,3.953255e+05,0.502436,5.679690,1.708185,5.681079,2.173463,1.664418,0.179666,0.190083,0.342939,...,0.0,0.0,50.698248,34.106127,2.105231,NaN,18.767165,11.811388,0.208636,0.213329
min,3.359820e+05,1.000000,0.000000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,0.000000,...,6.0,20.0,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000
25%,5.483720e+05,1.000000,4.000000,2.000000,4.500000,2.000000,0.000000,1.000000,1.000000,0.000000,...,6.0,20.0,36.000000,29.000000,1.000000,NaN,4.000000,5.000000,0.000000,0.000000
50%,1.082639e+06,1.000000,9.000000,3.000000,9.400000,3.000000,1.000000,1.000000,1.000000,0.000000,...,6.0,20.0,74.000000,58.000000,2.000000,NaN,13.000000,11.000000,0.000000,0.000000
75%,1.304103e+06,2.000000,14.000000,5.000000,14.400000,5.000000,1.000000,1.000000,1.000000,0.000000,...,6.0,20.0,115.000000,88.000000,4.000000,NaN,27.000000,20.000000,0.000000,0.000000
max,1.535465e+06,6.000000,19.000000,7.000000,19.600000,11.000000,6.000000,1.000000,1.000000,7.000000,...,6.0,20.0,287.000000,121.000000,10.000000,NaN,175.000000,73.000000,1.000000,1.000000

In [8]:
pd.set_option('display.max_columns',None)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 295732 entries, 0 to 295731
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           295732 non-null  int64
 1   date               295732 non-null  str
 2   match_type         295732 non-null  str
 3   event_name         295732 non-null  str
 4   innings            295732 non-null  int64
 5   batting_team       295732 non-null  str
 6   bowling_team       295732 non-null  str
 7   over               295732 non-null  int64
 8   ball               295732 non-null  int64
 9   ball_no            295732 non-null  float64
 10  batter             295732 non-null  str
 11  bat_pos            295732 non-null  int64
 12  runs_batter        295732 non-null  int64
 13  balls_faced        295732 non-null  int64
 14  bowler             295732 non-null  str
 15  valid_ball         295732 non-null  int64
 16  runs_extras        295732 non-null  int64
 17  runs_total         295732 non-null  int64
 18  runs_bowler        295732 non-null  int64
 19  runs_not_boundary  295732 non-null  bool
 20  extra_type         16227 non-null   str
 21  non_striker        295732 non-null  str
 22  non_striker_pos    295732 non-null  int64
 23  wicket_kind        14705 non-null   str
 24  player_out         14705 non-null   str
 25  fielders           10721 non-null   str
 26  runs_target        142303 non-null  float64
 27  review_batter      990 non-null     str
 28  team_reviewed      990 non-null     str
 29  review_decision    990 non-null     str
 30  umpire             990 non-null     str
 31  umpires_call       295732 non-null  bool
 32  player_of_match    295732 non-null  str
 33  match_won_by       295732 non-null  str
 34  win_outcome        290752 non-null  str
 35  toss_winner        295732 non-null  str
 36  toss_decision      295732 non-null  str
 37  venue              295732 non-null  str
 38  city               295732 non-null  str
 39  day                295732 non-null  int64
 40  month              295732 non-null  int64
 41  year               295732 non-null  int64
 42  season             295732 non-null  object
 43  gender             295732 non-null  str
 44  team_type          295732 non-null  str
 45  superover_winner   4152 non-null    str
 46  result_type        4980 non-null    str
 47  method             4131 non-null    str
 48  balls_per_over     295732 non-null  int64
 49  overs              295732 non-null  int64
 50  event_match_no     295732 non-null  object
 51  stage              295732 non-null  str
 52  match_number       295732 non-null  str
 53  team_runs          295732 non-null  int64
 54  team_balls         295732 non-null  int64
 55  team_wicket        295732 non-null  int64
 56  new_batter         14163 non-null   str
 57  power_surge_start  0 non-null       float64
 58  batter_runs        295732 non-null  int64
 59  batter_balls       295732 non-null  int64
 60  bowler_wicket      295732 non-null  int64
 61  batting_partners   295732 non-null  str
 62  striker_out        295732 non-null  int64
 63  next_batter        14163 non-null   str
dtypes: bool(2), float64(3), int64(24), object(2), str(33)
memory usage: 140.5+ MB

In [10]:
df['match_type'].unique()

<StringArray>
['T20']
Length: 1, dtype: str

In [11]:
df['season'].unique()

array(['2007/08', '2009', 2009, '2009/10', '2011', 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019, '2019', '2020/21', '2021', 2021,
       2022, 2023, 2024, 2025, 2026], dtype=object)

In [12]:
df['batting_team'].unique()

<StringArray>
[      'Kolkata Knight Riders', 'Royal Challengers Bangalore',
         'Chennai Super Kings',             'Kings XI Punjab',
            'Rajasthan Royals',            'Delhi Daredevils',
              'Mumbai Indians',             'Deccan Chargers',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
        'Lucknow Super Giants',              'Gujarat Titans',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

In [13]:
df['batter'].nunique()

738

In [14]:
df['bowler'].nunique()

577

In [15]:
df.isnull().sum()

match_id                 0
date                     0
match_type               0
event_name               0
innings                  0
                     ...
batter_balls             0
bowler_wicket            0
batting_partners         0
striker_out              0
next_batter         281569
Length: 64, dtype: int64

In [16]:
df.isnull().sum().sort_values(ascending=True)

match_id                  0
date                      0
match_type                0
event_name                0
innings                   0
                      ...
review_batter        294742
umpire               294742
review_decision      294742
team_reviewed        294742
power_surge_start    295732
Length: 64, dtype: int64

In [17]:
missing_percentage = (df.isnull().sum()/len(df)) * 100
missing_percentage.sort_values(ascending=False)

power_surge_start    100.000000
review_batter         99.665237
review_decision       99.665237
umpire                99.665237
team_reviewed         99.665237
                        ...
batter_runs            0.000000
batter_balls           0.000000
bowler_wicket          0.000000
batting_partners       0.000000
striker_out            0.000000
Length: 64, dtype: float64

In [18]:
missing = df.isnull().sum()
missing[missing>0].sort_values(ascending=False)

power_surge_start    295732
team_reviewed        294742
review_batter        294742
review_decision      294742
umpire               294742
method               291601
superover_winner     291580
result_type          290752
fielders             285011
new_batter           281569
next_batter          281569
wicket_kind          281027
player_out           281027
extra_type           279505
runs_target          153429
win_outcome            4980
dtype: int64

In [19]:
missing_percentage2 = (missing[missing>0]/len(df))*100
missing_percentage2.sort_values(ascending=False)

power_surge_start    100.000000
team_reviewed         99.665237
review_batter         99.665237
review_decision       99.665237
umpire                99.665237
method                98.603127
superover_winner      98.596026
result_type           98.316043
fielders              96.374758
new_batter            95.210867
next_batter           95.210867
wicket_kind           95.027593
player_out            95.027593
extra_type            94.512937
runs_target           51.881095
win_outcome            1.683957
dtype: float64

In [20]:
columns_to_drop = [
    'power_surge_start',
    'team_reviewed',
    'review_batter',
    'review_decision',
    'umpire',
    'new_batter',
    'next_batter'
]
df = df.drop(columns = columns_to_drop)

In [21]:
df.isnull().sum().sort_values(ascending=False)

method               291601
superover_winner     291580
result_type          290752
fielders             285011
player_out           281027
wicket_kind          281027
extra_type           279505
runs_target          153429
win_outcome            4980
ball                      0
over                      0
bowling_team              0
ball_no                   0
balls_faced               0
batter                    0
bat_pos                   0
runs_batter               0
runs_extras               0
valid_ball                0
date                      0
innings                   0
batting_team              0
match_type                0
event_name                0
match_id                  0
non_striker               0
non_striker_pos           0
runs_bowler               0
runs_not_boundary         0
runs_total                0
bowler                    0
player_of_match           0
umpires_call              0
venue                     0
city                      0
day                       0
month                     0
year                      0
match_won_by              0
toss_winner               0
toss_decision             0
team_type                 0
gender                    0
season                    0
balls_per_over            0
overs                     0
event_match_no            0
stage                     0
match_number              0
team_runs                 0
team_balls                0
team_wicket               0
batter_runs               0
batter_balls              0
bowler_wicket             0
batting_partners          0
striker_out               0
dtype: int64

In [22]:
df['win_outcome'].unique

<bound method Series.unique of 0          140 runs
1          140 runs
2          140 runs
3          140 runs
4          140 runs
            ...
295727    5 wickets
295728    5 wickets
295729    5 wickets
295730    5 wickets
295731    5 wickets
Name: win_outcome, Length: 295732, dtype: str>

In [23]:
df['win_outcome'].value_counts(dropna=False)

win_outcome
6 wickets    33237
7 wickets    30455
5 wickets    26905
8 wickets    20523
4 wickets    16021
             ...
89 runs        215
138 runs       212
146 runs       211
76 runs        204
112 runs       189
Name: count, Length: 115, dtype: int64

In [24]:
df[df['win_outcome'].isnull()][
    ['match_id', 'season', 'batting_team', 'bowling_team', 'match_won_by', 'win_outcome']
].head(20)

,match_id,season,batting_team,bowling_team,match_won_by,win_outcome
15161,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15162,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15163,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15164,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15165,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15166,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15167,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15168,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15169,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15170,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15171,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15172,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15173,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15174,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15175,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15176,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15177,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15178,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15179,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15180,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN

In [25]:
df[df['win_outcome'].isnull()][
    ['match_id', 'season', 'batting_team', 'bowling_team',
     'match_won_by', 'win_outcome']
].drop_duplicates().head(20)

,match_id,season,batting_team,bowling_team,match_won_by,win_outcome
15161,392190,2009,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
15287,392190,2009,Kolkata Knight Riders,Rajasthan Royals,Unknown,NaN
30707,419121,2009/10,Kings XI Punjab,Chennai Super Kings,Unknown,NaN
30829,419121,2009/10,Chennai Super Kings,Kings XI Punjab,Unknown,NaN
57068,501265,2011,Delhi Daredevils,Pune Warriors,Unknown,NaN
77794,598004,2013,Royal Challengers Bangalore,Sunrisers Hyderabad,Unknown,NaN
77917,598004,2013,Sunrisers Hyderabad,Royal Challengers Bangalore,Unknown,NaN
81200,598017,2013,Delhi Daredevils,Royal Challengers Bangalore,Unknown,NaN
81324,598017,2013,Royal Challengers Bangalore,Delhi Daredevils,Unknown,NaN
98800,729315,2014,Rajasthan Royals,Kolkata Knight Riders,Unknown,NaN
98923,729315,2014,Kolkata Knight Riders,Rajasthan Royals,Unknown,NaN
113004,829741,2015,Rajasthan Royals,Kings XI Punjab,Unknown,NaN
113130,829741,2015,Kings XI Punjab,Rajasthan Royals,Unknown,NaN
115353,829763,2015,Royal Challengers Bangalore,Rajasthan Royals,Unknown,NaN
121177,829813,2015,Delhi Daredevils,Royal Challengers Bangalore,Unknown,NaN
121300,829813,2015,Royal Challengers Bangalore,Delhi Daredevils,Unknown,NaN
144440,1082625,2017,Gujarat Lions,Mumbai Indians,Unknown,NaN
144569,1082625,2017,Mumbai Indians,Gujarat Lions,Unknown,NaN
166931,1175365,2019,Kolkata Knight Riders,Delhi Capitals,Unknown,NaN
167055,1175365,2019,Delhi Capitals,Kolkata Knight Riders,Unknown,NaN

In [26]:
df[df['win_outcome'].isnull()]['match_id'].nunique()

25

In [28]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.duplicated(
    subset=['match_id', 'innings', 'over', 'ball'],
    keep=False
).sum()

np.int64(21493)

In [31]:
duplicate_balls = df[df.duplicated(subset = ['match_id','innings','over','ball'], keep = False)]

duplicate_balls[['match_id', 'innings', 'over', 'ball',
     'batter', 'bowler', 'runs_batter',
     'runs_extras', 'runs_total', 'extra_type']].head(20)

,match_id,innings,over,ball,batter,bowler,runs_batter,runs_extras,runs_total,extra_type
2,335982,1,0,3,BB McCullum,P Kumar,0,1,1,wides
3,335982,1,0,3,BB McCullum,P Kumar,0,0,0,NaN
19,335982,1,3,1,BB McCullum,AA Noffke,0,5,5,wides
20,335982,1,3,1,BB McCullum,AA Noffke,6,0,6,NaN
78,335982,1,12,5,BB McCullum,JH Kallis,0,1,1,wides
79,335982,1,12,5,BB McCullum,JH Kallis,4,0,4,NaN
91,335982,1,14,5,BB McCullum,CL White,0,2,2,wides
92,335982,1,14,5,DJ Hussey,CL White,1,0,1,NaN
125,335982,2,0,2,W Jaffer,AB Dinda,0,1,1,wides
126,335982,2,0,2,W Jaffer,AB Dinda,0,0,0,NaN
141,335982,2,2,5,W Jaffer,AB Dinda,0,1,1,wides
142,335982,2,2,5,W Jaffer,AB Dinda,0,0,0,NaN
165,335982,2,6,4,MV Boucher,AB Agarkar,0,1,1,wides
166,335982,2,6,4,MV Boucher,AB Agarkar,0,1,1,wides
167,335982,2,6,4,MV Boucher,AB Agarkar,0,0,0,NaN
179,335982,2,8,4,AA Noffke,AB Agarkar,0,1,1,wides
180,335982,2,8,4,AA Noffke,AB Agarkar,0,1,1,wides
181,335982,2,8,4,AA Noffke,AB Agarkar,1,0,1,NaN
187,335982,2,9,4,P Kumar,SC Ganguly,0,1,1,wides
188,335982,2,9,4,P Kumar,SC Ganguly,0,1,1,legbyes